// Reads the Assisty architecture workflow result (JSON) and writes each authored
// document to the project folder. Usage:
//   node extract-docs.js "<path-to-task-output-file>" "D:\\Assisty"
const fs = require('fs');
const path = require('path');

const OUT = process.argv[2];
const DEST = process.argv[3] || 'D:\\Assisty';

if (!OUT || !fs.existsSync(OUT)) {
  console.error('Output file not found:', OUT);
  process.exit(1);
}

let raw = fs.readFileSync(OUT, 'utf8');

// The file should be the JSON result object. Be tolerant of any wrapper text.
let parsed;
try {
  parsed = JSON.parse(raw);
} catch (e) {
  const start = raw.indexOf('{');
  const end = raw.lastIndexOf('}');
  if (start === -1 || end === -1) {
    console.error('No JSON object found in output file.');
    process.exit(1);
  }
  try {
    parsed = JSON.parse(raw.slice(start, end + 1));
  } catch (e2) {
    console.error('JSON parse failed:', e2.message);
    process.exit(1);
  }
}

// The task output wraps the workflow return value under `result`.
const data = (parsed && parsed.result && (parsed.result.docs || parsed.result.winner)) ? parsed.result : parsed;

const written = [];
const w = (rel, content) => {
  const target = path.join(DEST, rel);
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, content, 'utf8');
  written.push(target + '  (' + content.length + ' chars)');
};

// 1) Research brief
if (data.briefText) {
  w(path.join('docs', '00-research-brief.md'), '# Assisty — Research Brief\n\n' + data.briefText + '\n');
}

// 2) Authored docs
const docs = Array.isArray(data.docs) ? data.docs : [];
for (const d of docs) {
  if (!d || !d.filename || !d.markdown) continue;
  w(d.filename, d.markdown.endsWith('\n') ? d.markdown : d.markdown + '\n');
}

// 3) Critique -> review doc
if (data.critique) {
  const c = data.critique;
  let md = '# Assisty — Architecture Review: Gaps, Risks & Open Decisions\n\n';
  md += '> Auto-generated by the completeness-critic pass of the architecture workflow.\n\n';
  if (c.verdict) md += '## Verdict\n\n' + c.verdict + '\n\n';
  const sec = (title, arr) => {
    if (Array.isArray(arr) && arr.length) {
      md += '## ' + title + '\n\n' + arr.map(x => '- ' + x).join('\n') + '\n\n';
    }
  };
  sec('Gaps to close', c.gaps);
  sec('Contradictions', c.contradictions);
  sec('Open product decisions for you', c.openProductDecisions);
  sec('Top risks', c.topRisks);
  w(path.join('docs', '07-review-gaps-risks.md'), md);
}

// 4) Decision record (winner + scores + grafted ideas)
if (data.winner) {
  const wn = data.winner;
  let md = '# Assisty — Architecture Decision Record (ADR-0001)\n\n';
  md += '**Chosen architecture:** ' + (wn.name || '') + '\n\n';
  if (wn.philosophy) md += '## Why (philosophy)\n\n' + wn.philosophy + '\n\n';
  if (wn.mvpTimeWeeks) md += '**Estimated MVP time:** ~' + wn.mvpTimeWeeks + ' weeks\n\n';
  if (wn.monthlyCostEstimate) md += '**Estimated monthly cost:** ' + wn.monthlyCostEstimate + '\n\n';
  if (Array.isArray(data.scoreTally) && data.scoreTally.length) {
    md += '## Judge panel scores (avg of 3 reviewers, max 60)\n\n';
    md += '| Candidate | Avg score |\n|---|---|\n';
    data.scoreTally
      .slice()
      .sort((a, b) => (b.avg || 0) - (a.avg || 0))
      .forEach(s => { md += '| ' + s.name + ' | ' + (Math.round((s.avg || 0) * 10) / 10) + ' |\n'; });
    md += '\n';
  }
  if (Array.isArray(data.graft) && data.graft.length) {
    md += '## Best ideas grafted in from the runner-up designs\n\n';
    md += data.graft.map(x => '- ' + x).join('\n') + '\n';
  }
  w(path.join('docs', 'ADR-0001-architecture-choice.md'), md);
}

console.log('WINNER: ' + (data.winner && data.winner.name));
console.log('FILES WRITTEN (' + written.length + '):');
written.forEach(x => console.log('  - ' + x));
