export const meta = {
  name: 'assisty-scaffold-mvp',
  description: 'Scaffold the Assisty MVP monorepo: NestJS monolith + postgres.js + pg-boss + LiteLLM + simple RAG + Docker Compose + Railway. Simplicity & reliability first.',
  phases: [
    { title: 'Scaffold', detail: 'parallel authors write coherent, buildable files to D:\\Assisty per the shared spec' },
  ],
}

const AUTHOR_SCHEMA = {
  type: 'object',
  properties: {
    group: { type: 'string' },
    filesWritten: { type: 'array', items: { type: 'string' } },
    notes: { type: 'string' },
  },
  required: ['group', 'filesWritten'],
  additionalProperties: false,
}

// ============================ SHARED SPEC ============================
const SPEC = [
  'ASSISTY MVP SCAFFOLD — SHARED SPEC (every author MUST follow this exactly for cross-file coherence).',
  '',
  'PRODUCT PRINCIPLE: "Assisty should feel glitch-free, fast, and reliable." Prioritize implementation simplicity, reliability, maintainability, Docker-first dev, stable deploys. Monolith. Minimal abstractions. Strong structured logging. Idempotent webhooks. Stable retries. NO Kubernetes, NO microservices, NO LangGraph, NO heavy orchestration.',
  '',
  'TARGET FLOW: Flutter App -> NestJS API (monolith) -> Supabase Postgres -> LiteLLM proxy -> AI models (OpenAI, Gemini, OpenRouter).',
  '',
  'STACK (pin these): Node >=20, NestJS 11, TypeScript 5.7, postgres.js (npm "postgres") for DB, raw SQL migrations, pg-boss for the job queue (Postgres-backed, NO Redis), nestjs-pino for logging, zod for config validation, openai SDK pointed at the LiteLLM proxy for chat+embeddings. Docker Compose for local dev. Railway for deploy.',
  '',
  'ALL CODE GOES UNDER D:\\Assisty. Use the Write tool to create each file at its absolute Windows path (e.g. D:\\Assisty\\backend\\src\\main.ts). Write COMPLETE, COMPILABLE TypeScript — no TODO stubs in critical paths. Follow NestJS 11 conventions (standalone-ish modules, dependency injection, decorators).',
  '',
  'REPO LAYOUT:',
  '  D:\\Assisty\\',
  '    docker-compose.yml          (postgres+pgvector, litellm, api)',
  '    .env.example                (all env vars; NO real secrets)',
  '    .dockerignore',
  '    railway.json                (Railway deploy config for backend)',
  '    docs/DEPLOY.md',
  '    .github/workflows/ci.yml',
  '    infra/litellm/config.yaml   (LiteLLM model_list: openai, gemini, openrouter, embeddings)',
  '    app/README.md               (Flutter app placeholder — built in a later phase)',
  '    supabase/migrations/0001_init.sql',
  '    backend/                    (the NestJS monolith)',
  '      package.json tsconfig.json tsconfig.build.json nest-cli.json Dockerfile .eslintrc.cjs .prettierrc',
  '      scripts/migrate.ts',
  '      src/main.ts',
  '      src/app.module.ts',
  '      src/config/configuration.ts  src/config/env.validation.ts',
  '      src/health/health.controller.ts  src/health/health.module.ts',
  '      src/database/database.module.ts  src/database/database.service.ts',
  '      src/database/repositories/{tenants,channel-connections,conversations,messages,kb,usage,webhook-events}.repository.ts',
  '      src/queue/queue.module.ts  src/queue/queue.service.ts  src/queue/queue.constants.ts',
  '      src/channels/channel.types.ts',
  '      src/channels/whatsapp/whatsapp.module.ts  whatsapp.controller.ts  whatsapp.service.ts  whatsapp.signature.ts',
  '      src/ai/ai.module.ts  ai.service.ts  ai.models.ts',
  '      src/rag/rag.module.ts  rag.service.ts',
  '      src/conversations/conversations.module.ts  inbound.processor.ts',
  '',
  'EXACT backend/package.json (backend-core MUST write this verbatim):',
  '{',
  '  "name": "assisty-backend",',
  '  "version": "0.1.0",',
  '  "private": true,',
  '  "engines": { "node": ">=20" },',
  '  "scripts": {',
  '    "build": "nest build",',
  '    "start": "node dist/main.js",',
  '    "start:dev": "nest start --watch",',
  '    "start:prod": "node dist/main.js",',
  '    "migrate": "ts-node scripts/migrate.ts",',
  '    "lint": "eslint \\"src/**/*.ts\\" --fix",',
  '    "format": "prettier --write \\"src/**/*.ts\\"",',
  '    "test": "jest --passWithNoTests"',
  '  },',
  '  "dependencies": {',
  '    "@nestjs/common": "^11.0.1",',
  '    "@nestjs/config": "^4.0.0",',
  '    "@nestjs/core": "^11.0.1",',
  '    "@nestjs/platform-express": "^11.0.1",',
  '    "nestjs-pino": "^4.3.0",',
  '    "openai": "^4.77.0",',
  '    "pg-boss": "^10.1.6",',
  '    "pino": "^9.6.0",',
  '    "pino-http": "^10.4.0",',
  '    "postgres": "^3.4.5",',
  '    "reflect-metadata": "^0.2.2",',
  '    "rxjs": "^7.8.1",',
  '    "zod": "^3.24.1"',
  '  },',
  '  "devDependencies": {',
  '    "@nestjs/cli": "^11.0.0",',
  '    "@nestjs/schematics": "^11.0.0",',
  '    "@nestjs/testing": "^11.0.1",',
  '    "@types/express": "^5.0.0",',
  '    "@types/jest": "^29.5.14",',
  '    "@types/node": "^22.10.0",',
  '    "@types/supertest": "^6.0.2",',
  '    "eslint": "^9.17.0",',
  '    "jest": "^29.7.0",',
  '    "pino-pretty": "^13.0.0",',
  '    "prettier": "^3.4.2",',
  '    "source-map-support": "^0.5.21",',
  '    "supertest": "^7.0.0",',
  '    "ts-jest": "^29.2.5",',
  '    "ts-node": "^10.9.2",',
  '    "typescript": "^5.7.2"',
  '  }',
  '}',
  '',
  'tsconfig.json: commonjs module, moduleResolution node, target ES2022, experimentalDecorators true, emitDecoratorMetadata true, strictNullChecks true, esModuleInterop true, skipLibCheck true, outDir ./dist, baseUrl ./, sourceMap true, declaration false. nest-cli.json: standard with "sourceRoot":"src". tsconfig.build.json extends tsconfig and excludes test files.',
  '',
  'CONFIG (src/config): use @nestjs/config ConfigModule.forRoot({ isGlobal:true, load:[configuration], validate }). env.validation.ts uses zod to parse process.env and throw on missing required vars. Required env vars (names FIXED):',
  '  NODE_ENV, PORT(default 3000), LOG_LEVEL(default info),',
  '  DATABASE_URL  (postgres connection string),',
  '  LITELLM_BASE_URL (e.g. http://litellm:4000/v1), LITELLM_API_KEY,',
  '  DEFAULT_CHAT_MODEL (default "gpt-4o-mini"), EMBEDDING_MODEL (default "text-embedding-3-small"), EMBEDDING_DIM (default 1536),',
  '  WHATSAPP_VERIFY_TOKEN, WHATSAPP_APP_SECRET, WHATSAPP_GRAPH_VERSION(default v21.0).',
  '  (Per-tenant WhatsApp access tokens + phone_number_id live in DB channel_connections, NOT env — but allow a fallback WHATSAPP_ACCESS_TOKEN + WHATSAPP_PHONE_NUMBER_ID env for single-tenant dev.)',
  'configuration.ts returns a typed nested config object. Provide a typed AppConfig and read via ConfigService.',
  '',
  'LOGGING: nestjs-pino. In app.module import LoggerModule.forRoot({ pinoHttp: { level: LOG_LEVEL, transport: NODE_ENV!=="production" ? { target: "pino-pretty" } : undefined, redact: ["req.headers.authorization","req.headers[\'x-hub-signature-256\']"] } }). In main.ts: app.useLogger(app.get(Logger)) from nestjs-pino. Log every webhook receipt, job start/finish, and failures with context (tenantId, wamid, jobId). Never log secrets/tokens.',
  '',
  'main.ts: const app = await NestFactory.create(AppModule, { rawBody: true, bufferLogs: true }); app.useLogger(app.get(Logger)); app.enableShutdownHooks(); await app.listen(process.env.PORT || 3000). (rawBody:true is REQUIRED for WhatsApp HMAC verification.)',
  '',
  'app.module.ts imports IN THIS ORDER: ConfigModule (global via forRoot), LoggerModule (pino), DatabaseModule, QueueModule, HealthModule, WhatsappModule, AiModule, RagModule, ConversationsModule. DatabaseModule and QueueModule are @Global() so their services inject anywhere without re-import.',
  '',
  'DATABASE (postgres.js): DatabaseService wraps a single postgres() client from DATABASE_URL (config: { max: 10, prepare: false }) — expose as readonly sql. Implement onModuleDestroy -> sql.end(). DatabaseModule is @Global, provides+exports DatabaseService AND all repositories. Repositories take DatabaseService via DI. EVERY query that touches tenant data MUST filter by tenant_id (app-level tenant scoping; document that Postgres RLS is a later hardening step). Repository contracts (method signatures FIXED):',
  '  TenantsRepository: findById(id), create(name)',
  '  ChannelConnectionsRepository: findByExternalId(type, externalId) -> {id, tenantId, type, externalId, accessToken, phoneNumberId, status} | null; findById(id)',
  '  ConversationsRepository: findOrCreate(tenantId, channelConnectionId, customerExternalId) -> {id,...}; touch(id)',
  '  MessagesRepository: existsByChannelMessageId(channelMessageId)->boolean; insertInbound({tenantId,conversationId,channelMessageId,content})->row; insertOutbound({tenantId,conversationId,content,model,tokens})->row; recentByConversation(conversationId, limit) -> array oldest..newest',
  '  KbRepository: searchChunks(tenantId, embedding(number[]), k) -> [{content, similarity}]; insertChunk(tenantId, documentId, content, embedding)',
  '  UsageRepository: record(tenantId, kind, amount)',
  '  WebhookEventsRepository: tryClaim(provider, eventId) -> boolean (INSERT ... ON CONFLICT DO NOTHING; returns true if the row was newly inserted = first time, false if duplicate)',
  'Embeddings stored as pgvector. To query vector with postgres.js, format the JS number[] as a vector literal string and cast, e.g. WHERE ... ORDER BY embedding <=> (the-literal)::vector. Provide a small helper to turn number[] into the "[0.1,0.2,...]" string.',
  '',
  'MIGRATION supabase/migrations/0001_init.sql (raw SQL, idempotent with IF NOT EXISTS):',
  '  CREATE EXTENSION IF NOT EXISTS vector;',
  '  CREATE EXTENSION IF NOT EXISTS "pgcrypto"; (for gen_random_uuid)',
  '  tenants(id uuid pk default gen_random_uuid(), name text not null, created_at timestamptz default now())',
  '  users(id uuid pk, tenant_id uuid fk->tenants, email text, supabase_uid text unique, role text default \'owner\', created_at)',
  '  channel_connections(id uuid pk, tenant_id uuid fk, type text check in (whatsapp,web,email,messenger,instagram,tiktok), external_id text, access_token text, phone_number_id text, status text default \'active\', created_at, UNIQUE(type, external_id))',
  '  conversations(id uuid pk, tenant_id uuid fk, channel_connection_id uuid fk, customer_external_id text, status text default \'open\', last_message_at timestamptz, created_at, UNIQUE(channel_connection_id, customer_external_id))',
  '  messages(id uuid pk, tenant_id uuid fk, conversation_id uuid fk, direction text check (inbound/outbound), role text, channel_message_id text, content text, model text, tokens int, created_at) with UNIQUE(channel_message_id) WHERE channel_message_id is not null (use a partial unique index)',
  '  kb_documents(id uuid pk, tenant_id uuid fk, type text, title text, source text, status text default \'approved\', content text, content_hash text, created_at, updated_at)',
  '  kb_chunks(id uuid pk, tenant_id uuid fk, document_id uuid fk, content text, embedding vector(1536), created_at)',
  '  usage_ledger(id uuid pk, tenant_id uuid fk, kind text, amount numeric, created_at)',
  '  webhook_events(id uuid pk default gen_random_uuid(), provider text, event_id text, received_at timestamptz default now(), UNIQUE(provider, event_id))',
  '  Indexes: every tenant_id; conversations(tenant_id); messages(conversation_id); kb_chunks USING ivfflat (embedding vector_cosine_ops) WITH (lists=100) (or hnsw); kb_chunks(tenant_id).',
  '  Note: pg-boss creates its own schema automatically on boot; do NOT create pgboss tables here.',
  'scripts/migrate.ts: read every .sql file in ../supabase/migrations sorted by name, run each within the postgres.js client from DATABASE_URL, log applied files, exit 0/1. Keep it dead simple (no migration-tracking table needed for MVP, rely on IF NOT EXISTS idempotency).',
  '',
  'QUEUE (pg-boss): queue.constants.ts exports QUEUES = { INBOUND_MESSAGE: "inbound-message" }. QueueService (@Global module): on onModuleInit -> new PgBoss(DATABASE_URL); await boss.start(); on onModuleDestroy -> boss.stop({graceful:true}). Methods: enqueue(name, data, opts) -> boss.send(name, data, { retryLimit: 5, retryBackoff: true, ...opts }); work(name, handler) -> boss.work(name, { batchSize:1 }, handler). Idempotency: rely on WebhookEventsRepository.tryClaim at ingest + messages.channel_message_id unique at processing. Strong try/catch + logging inside handlers; rethrow to let pg-boss retry.',
  '',
  'CHANNELS: channel.types.ts defines a minimal NormalizedInboundMessage {tenantId, channelConnectionId, channelType, customerExternalId, channelMessageId, text, raw} and an InboundJobData (the pg-boss payload). Keep the channel abstraction MINIMAL (one interface) — do not over-abstract.',
  '',
  'WHATSAPP MODULE:',
  '  whatsapp.signature.ts: verifySignature(appSecret, rawBody: Buffer, headerValue: string): boolean using crypto.createHmac sha256, compare to "sha256=" + hex via crypto.timingSafeEqual (guard length).',
  '  whatsapp.controller.ts: @Controller("webhooks/whatsapp"). GET "" -> verify: read query hub.mode, hub.verify_token, hub.challenge; if mode==="subscribe" and token===WHATSAPP_VERIFY_TOKEN return challenge (raw string, 200) else 403. POST "" -> use @Req() req: RawBodyRequest<Request>; verify signature against req.rawBody (403 on fail); ALWAYS return 200 quickly; for each message in the payload: resolve channel_connection by phone_number_id (metadata.phone_number_id) -> tenant; call WebhookEventsRepository.tryClaim("whatsapp", wamid) — if duplicate, skip; else enqueue INBOUND_MESSAGE job with normalized data. Do NO LLM work here. Wrap processing so a parse error never prevents the 200.',
  '  whatsapp.service.ts: parseWebhook(body) -> NormalizedInboundMessage[] (handle entry[].changes[].value.messages[]; text.body; from; id=wamid; metadata.phone_number_id). sendText(connection, to, text): POST https://graph.facebook.com/{GRAPH_VERSION}/{phone_number_id}/messages with Authorization Bearer access_token, JSON { messaging_product:"whatsapp", to, type:"text", text:{ body } } using global fetch; log + throw on non-2xx.',
  '  whatsapp.module.ts: imports nothing special (Database+Queue are global); provides WhatsappService; controller WhatsappController; exports WhatsappService.',
  '',
  'AI MODULE:',
  '  ai.models.ts: export the model ids and a helper resolveChatModel(requested?) defaulting to DEFAULT_CHAT_MODEL. Document that adding Anthropic = adding one entry in infra/litellm/config.yaml, no code change.',
  '  ai.service.ts: construct an OpenAI client ({ baseURL: LITELLM_BASE_URL, apiKey: LITELLM_API_KEY }). chat({model, messages, temperature?}) -> client.chat.completions.create(...); return { content, model, usageTokens }. embed(text|texts) -> client.embeddings.create({ model: EMBEDDING_MODEL, input }); return number[][] (or number[]). Strong error handling + a single retry on 429/5xx (simple, not fancy). Log model + token usage, never the full prompt content at info level.',
  '  ai.module.ts: provides+exports AiService.',
  '',
  'RAG MODULE (simple):',
  '  rag.service.ts: retrieve(tenantId, query, k=5) -> embed query via AiService -> KbRepository.searchChunks -> return array of {content, similarity}. buildContextBlock(chunks) -> a plain string for the system prompt (or "" if none). ingestText(tenantId, documentId, text) optional helper: naive chunk (~500 tokens by characters), embed, KbRepository.insertChunk. Keep chunking trivial for MVP.',
  '  rag.module.ts: imports AiModule; provides+exports RagService.',
  '',
  'CONVERSATIONS MODULE (the brain orchestration — deterministic, linear, NO LangGraph):',
  '  inbound.processor.ts: an @Injectable that onModuleInit registers QueueService.work(QUEUES.INBOUND_MESSAGE, handler). handler(job): { tenantId, conversationId-or-create, channelConnectionId, customerExternalId, channelMessageId, text }. Steps with try/catch + logging: (1) if MessagesRepository.existsByChannelMessageId -> skip (idempotent); (2) ConversationsRepository.findOrCreate; (3) MessagesRepository.insertInbound; (4) RagService.retrieve(tenantId, text); (5) build messages = [system prompt (assistant persona + "answer only from context, say you are not sure if unknown" + the RAG context block), ...MessagesRepository.recentByConversation mapped to roles, {role:user, content:text}]; (6) AiService.chat; (7) MessagesRepository.insertOutbound; (8) load channel_connection -> WhatsappService.sendText(connection, customerExternalId, reply); (9) UsageRepository.record(tenantId,"ai_tokens",usageTokens) and ("messages",1). On any failure: log with context and rethrow (pg-boss retries). Keep it readable top-to-bottom.',
  '  conversations.module.ts: imports AiModule, RagModule, WhatsappModule; provides InboundProcessor.',
  '',
  'HEALTH: health.controller.ts GET /health -> { status:"ok", uptime, timestamp } and a /health/db that runs SELECT 1 via DatabaseService. health.module.ts.',
  '',
  'DOCKER: backend/Dockerfile multi-stage (node:20-alpine; deps -> build -> runtime running node dist/main.js; copy package.json, npm ci, build). .dockerignore excludes node_modules, dist, .git. docker-compose.yml services: (1) postgres: image pgvector/pgvector:pg16, env POSTGRES_USER/PASSWORD/DB, volume pgdata, ports 5432:5432, healthcheck pg_isready; (2) litellm: image ghcr.io/berriai/litellm:main-stable, command "--config /app/config.yaml --port 4000", volume ./infra/litellm/config.yaml:/app/config.yaml, env passthrough of OPENAI_API_KEY/GEMINI_API_KEY/OPENROUTER_API_KEY/LITELLM_MASTER_KEY, ports 4000:4000; (3) api: build ./backend (target dev), command "npm run start:dev", volumes ./backend:/app and /app/node_modules, env_file .env, depends_on postgres(healthy)+litellm, ports 3000:3000. Use a single .env at repo root for compose.',
  '',
  'infra/litellm/config.yaml: model_list with entries: gpt-4o-mini (openai/gpt-4o-mini, api_key os.environ/OPENAI_API_KEY), gemini-1.5-flash (gemini/gemini-1.5-flash, api_key os.environ/GEMINI_API_KEY), an openrouter example (openrouter/openai/gpt-4o-mini or similar, api_key os.environ/OPENROUTER_API_KEY), and text-embedding-3-small (openai/text-embedding-3-small). general_settings master_key os.environ/LITELLM_MASTER_KEY. Add a comment: "Add Anthropic here later — one entry, no code change."',
  '',
  '.env.example: list EVERY env var with placeholder values and short comments, including the compose-only POSTGRES_* and the AI provider keys (OPENAI_API_KEY, GEMINI_API_KEY, OPENROUTER_API_KEY, LITELLM_MASTER_KEY) and DATABASE_URL pointing at the compose postgres (postgresql://assisty:assisty@localhost:5432/assisty for host, or @postgres:5432 inside compose). NO real secrets.',
  '',
  'railway.json: { "$schema":"https://railway.app/railway.schema.json", "build": { "builder":"DOCKERFILE", "dockerfilePath":"backend/Dockerfile" }, "deploy": { "startCommand":"node dist/main.js", "restartPolicyType":"ON_FAILURE", "restartPolicyMaxRetries":10, "healthcheckPath":"/health" } }.',
  'docs/DEPLOY.md: explain local (docker compose up, npm run migrate), and Railway prod (Supabase hosted Postgres -> DATABASE_URL; LiteLLM either a second Railway service or point LITELLM_BASE_URL at OpenRouter directly; set env vars; deploy backend Dockerfile). Mention the WhatsApp webhook URL and Meta verify token setup.',
  '.github/workflows/ci.yml: on push/PR -> node 20 -> cd backend -> npm ci -> npm run build -> npm test. Keep it minimal and reliable.',
  'app/README.md: short note that the Flutter app (Riverpod 2, supabase_flutter, FCM) is scaffolded in the next phase; this folder is the placeholder.',
  '',
  'OUTPUT: write all your assigned files with the Write tool, then return { group, filesWritten:[absolute paths], notes }.',
].join('\n')

// ============================ AUTHORS ============================
const GROUPS = [
  {
    key: 'infra',
    files: 'docker-compose.yml, .dockerignore, .env.example, railway.json, docs/DEPLOY.md, .github/workflows/ci.yml, infra/litellm/config.yaml, app/README.md, and APPEND a "## Local development" + "## Deploy" section to the existing D:\\Assisty\\README.md (read it first, then Edit to append — do not delete existing content).',
  },
  {
    key: 'backend-core',
    files: 'backend/package.json (VERBATIM from spec), backend/tsconfig.json, backend/tsconfig.build.json, backend/nest-cli.json, backend/.eslintrc.cjs, backend/.prettierrc, backend/Dockerfile, backend/src/main.ts, backend/src/app.module.ts, backend/src/config/configuration.ts, backend/src/config/env.validation.ts, backend/src/health/health.controller.ts, backend/src/health/health.module.ts. app.module.ts MUST import every module named in the spec with the exact class names: ConfigModule, LoggerModule(nestjs-pino), DatabaseModule, QueueModule, HealthModule, WhatsappModule, AiModule, RagModule, ConversationsModule.',
  },
  {
    key: 'backend-db',
    files: 'backend/src/database/database.module.ts (@Global), backend/src/database/database.service.ts, backend/src/database/repositories/{tenants,channel-connections,conversations,messages,kb,usage,webhook-events}.repository.ts (each a class with the EXACT method signatures from the spec, registered as providers in DatabaseModule and exported), backend/src/database/vector.util.ts (number[] -> pgvector literal), supabase/migrations/0001_init.sql, backend/scripts/migrate.ts.',
  },
  {
    key: 'backend-queue',
    files: 'backend/src/queue/queue.constants.ts, backend/src/queue/queue.service.ts, backend/src/queue/queue.module.ts (@Global). QueueService uses pg-boss with DATABASE_URL from ConfigService, start on init, graceful stop on destroy, enqueue() with retryLimit:5+retryBackoff, and work().',
  },
  {
    key: 'backend-whatsapp',
    files: 'backend/src/channels/channel.types.ts, backend/src/channels/whatsapp/whatsapp.signature.ts, backend/src/channels/whatsapp/whatsapp.service.ts, backend/src/channels/whatsapp/whatsapp.controller.ts, backend/src/channels/whatsapp/whatsapp.module.ts. Controller: GET verify + POST webhook with HMAC over req.rawBody, dedupe via WebhookEventsRepository.tryClaim, enqueue INBOUND_MESSAGE, always 200. Also write a tiny unit test backend/src/channels/whatsapp/whatsapp.signature.spec.ts proving a known signature verifies and a wrong one fails (reliability).',
  },
  {
    key: 'backend-ai-rag',
    files: 'backend/src/ai/ai.models.ts, backend/src/ai/ai.service.ts, backend/src/ai/ai.module.ts, backend/src/rag/rag.service.ts, backend/src/rag/rag.module.ts, backend/src/conversations/inbound.processor.ts, backend/src/conversations/conversations.module.ts. AiService uses the openai SDK pointed at LITELLM_BASE_URL. InboundProcessor registers the pg-boss worker on init and runs the deterministic RAG->chat->reply->send->usage pipeline with strong logging + retry-on-throw.',
  },
]

phase('Scaffold')
const results = (await parallel(GROUPS.map(g => () =>
  agent(
    'You are a senior NestJS/TypeScript engineer scaffolding part of the Assisty MVP. Write COMPLETE, COMPILABLE files (no stubs in critical paths) that cohere with the rest of the monorepo per the shared spec.\n\n' +
    SPEC +
    '\n\n========================\nYOUR GROUP: ' + g.key + '\nWRITE EXACTLY THESE FILES (use the Write tool, absolute D:\\Assisty paths): ' + g.files +
    '\n\nDo not write files outside your group. Ensure every import path and class name matches the spec so the whole backend builds. Return { group, filesWritten, notes }.',
    { label: 'scaffold:' + g.key, phase: 'Scaffold', schema: AUTHOR_SCHEMA }
  )
))).filter(Boolean)

return {
  groups: results.map(r => ({ group: r.group, count: (r.filesWritten || []).length, files: r.filesWritten, notes: r.notes })),
}
